name: mlkit_scanner
description: A Flutter plugin to detect barcodes, text, faces, and objects using Google MLKit API for iOS and Android
version: 0.3.4
homepage: https://www.dns-tech.ru/
repository: https://github.com/dns-technologies/mlkit_scanner

environment:
  sdk: '>=2.14.3 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.dns_technologies.mlkit_scanner
        pluginClass: MlkitScannerPlugin
      ios:
        pluginClass: MlkitScannerPlugin


